### ISSUE TITLE
Dosent display if teamspeak is closed

### ISSUE THREAD

**Issue by Nubston** [EgoPvP/SaltyNUI#1]
The Display only appears if you are not in a correct channel if teamspeak is closed it just doesn't display which means it doesn't stop the user from playing without voice enabled

**Comment by ZockerBoysHD** [comment]
Have you done the Advanced Setup...

**Comment by Nubston** [comment]
yes but i will double check it as i am going to recompile tonight anyway so ill let you no if i maybe messed up

**Comment by ZockerBoysHD** [comment]
After u checked, maybe send me ur VoiceClient.cs file so i can check it. 
Had this issue with another Server and they had renamed some Events which caused the NUI to not work Properly. 

The OnDisconnected Event has to look something like this:
https://cdn.discordapp.com/attachments/713468409781813290/713471036355641444/Screenshot_87.png
