### ISSUE TITLE
Blackscreen bzw. Saltynui Problem

### ISSUE THREAD

**Issue by Makaveli4510** [EgoPvP/SaltyNUI#3]
Hey ich habe alle Schritte getan, die du beschrieben hast, damit Spieler die nicht mit Saltychat verbunden sind, mit einem Black screen konfrontiert werden. Den aller letzten Schritt mit dem neuhochladen verstehe ich nicht ganz. Habe es getan, aber es ändert sich nicht. Erst wenn jemand full mute ist, dann plopt das Blackscreen auf 👍  Wäre sehr nett wenn du ein fix finden würdest :D Hast du vllt TS oder DC für mich? Dann kann ich dir das ganze auch zeigen.

**Comment by ZockerBoysHD** [comment]
A ) Alle möglichkeiten stehen in der Readme
B) Laut Discord Aussagen Verdacht auf Nutzer-Fehler (wurde nicht Ordnungsgemäß umproigrammiert weder anschließend compilet?)

**Comment by ZockerBoysHD** [comment]
wegen keiner antworten mehr geschlossen
