### ISSUE TITLE
InstanceState.IsReady ist veraltet

### ISSUE THREAD

**Issue by Naifen-Phoxidas** [EgoPvP/SaltyNUI#4]
Bei der neusten SaltyChat version kommt beim Erstellen, dieser Hinwies:

```
> 1>------ Erstellen gestartet: Projekt: SaltyClient, Konfiguration: Debug Any CPU ------
> 1>C:\Users\ADMIN\Desktop\saltychat\SaltyClient\VoiceManager.cs(644,29,644,50): warning CS0612: '"InstanceState.IsReady" ist veraltet.
> 1>  SaltyClient -> C:\Users\ADMIN\Desktop\saltychat\SaltyClient\bin\Debug\SaltyClient.net.dll
> ========== Erstellen: 1 erfolgreich, 0 fehlerhaft, 0 aktuell, 0 übersprungen ==========
```

**Comment by Rediupside** [comment]
Gibt es mittlerweile einen Fix ?

**Comment by ZockerBoysHD** [comment]
> Bei der neusten SaltyChat version kommt beim Erstellen, dieser Hinwies:
> 
> ```
> > 1>------ Erstellen gestartet: Projekt: SaltyClient, Konfiguration: Debug Any CPU ------
> > 1>C:\Users\ADMIN\Desktop\saltychat\SaltyClient\VoiceManager.cs(644,29,644,50): warning CS0612: '"InstanceState.IsReady" ist veraltet.
> > 1>  SaltyClient -> C:\Users\ADMIN\Desktop\saltychat\SaltyClient\bin\Debug\SaltyClient.net.dll
> > ========== Erstellen: 1 erfolgreich, 0 fehlerhaft, 0 aktuell, 0 übersprungen ==========
> ```

dieser fehler ist nicht schweliegend und hintert weder saltychat noch saltynui an der funktion. 
Dazu ist das ein SaltyChat fehler, der nicht von mir kommt und somit kann ich da nix machen.

"veraltet" heist in dem falle hier, dass es unklar ist weil der InstanceState nun mehrere Statusse haben kann anstatt nur Ready oder nicht Ready.
