### ISSUE TITLE
Neuste Saltychat Server Version Swiss Channel

### ISSUE THREAD

**Issue by Maxamax1** [EgoPvP/SaltyNUI#5]
Hi, Habe mir heute die Neuste Saltychat Fivem Version für den Server geholt. Wenn ich nun einem Swiss channel betrete, kann ich nichts sehen, da dass Nui nicht verschwindet. Meine Frage ist, wo ich in der neuen version die Trigger von SaltyNui einfügen muss.

**Comment by Alfons44** [comment]
Wie vorher auch. Die Zeilenangabe kann aber variieren. Schau dir hierbei einfach mal die Screenshots an

**Comment by Maxamax1** [comment]
Habe die letzte Stunde eben intensiv danach gesucht und probiert, doch habe es nicht geschafft, da InstanceState mit GameInstanceState getauscht/ersetzt/umgeändert wurde
alt:
![image](https://user-images.githubusercontent.com/74760408/115130758-780dbb80-9ff2-11eb-9c16-b51e533e4df1.png)
neu:
![image](https://user-images.githubusercontent.com/74760408/115130772-8bb92200-9ff2-11eb-9aa6-c78172579cfe.png)
--
alt:
![image](https://user-images.githubusercontent.com/74760408/115130785-adb2a480-9ff2-11eb-961b-0fbf1a8dcc5b.png)
neu:
![image](https://user-images.githubusercontent.com/74760408/115130799-d0dd5400-9ff2-11eb-82cc-6bcf9783e8a4.png)

**Comment by Alfons44** [comment]
Meld dich mal bitte im Discord Support: https://discord.com/invite/qRc5Hbb

**Comment by ZockerBoysHD** [comment]
> Hi, Habe mir heute die Neuste Saltychat Fivem Version für den Server geholt. Wenn ich nun einem Swiss channel betrete, kann ich nichts sehen, da dass Nui nicht verschwindet. Meine Frage ist, wo ich in der neuen version die Trigger von SaltyNui einfügen muss.

alles ist in der readme angegeben zu den jeweiligen versionen.
