### ISSUE TITLE
Saltychat not recognised

### ISSUE THREAD

**Issue by KarliCarlos** [EgoPvP/SaltyNUI#7]
Hi,
when I join the Server, wheater I'm in a not Swiss Channel or not, the NUI-Screen doesn't disappear. 
Saltychat Addon Version: 2.3.6
Saltychat Server Version: 0.0.3
Used Advanced Setup
![image](https://user-images.githubusercontent.com/88288166/145677560-dce80231-891c-4f5c-9573-89d1b27fba8c.png)
![image](https://user-images.githubusercontent.com/88288166/145677565-837f2532-22e0-4d97-b8fd-ad23bcf79435.png)

**Comment by KarliCarlos** [comment]
Huch, hab gar nicht gesehen, dass du ein Deutscher bist xD. Also, wenn man dem Server joint bleibt der Screen bestehen und verschwindet nicht. Hatte vorher eine alte Saltychat Version installiert, bis ich vorher gemerkt hab, dass es eine neue gibt xD. Danke schon mal für die Hilfe im Vorraus

**Comment by KarliCarlos** [comment]
Man wird auch von Saltychat nicht mehr gemovt

**Comment by KarliCarlos** [comment]
Update: Mit Version 3.0.5 hat es auch nicht funktioniert. Könnte es sein, dass SaltyNui outdated ist?

**Comment by ZockerBoysHD** [comment]
SaltyNUI works on all SaltyChat versions, up to the Latest.

If you dont get moved,your saltychat isnt working properly.
Please make sure you dont get anny errors whilst compiling the ressource and it starts up properly

**Comment by KarliCarlos** [comment]
Ok danke

**Comment by KarliCarlos** [comment]
Hättest du irgendeine Idee, warum Saltychat nicht funktioniert?

**Comment by KarliCarlos** [comment]
Hab es hinbekommen. Vielen Dank trotzdem für die schnelle Antwort
